layout_spectrum: 0.6754677
typography_spectrum: 0.9772344
color:
  saturation: 0.7218286
  brandStrength: 0
  lightness: 0.8590778
  rhythmicContrast: 0.4989974
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: The Initiate
